apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: "*"
    helm:
      releaseName: metallb
      valueFiles:
      - ../metallb/values/helm-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
