apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb-applicationset
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/auto-sync: "true"
spec:
  project: metallb-project
  generators:
  # Generator 1: MetalLB Helm Chart
  - list:
      elements:
      - name: metallb-helm
        syncWave: "2"
        repoURL: https://metallb.github.io/metallb
        chart: metallb
        targetRevision: "*"
        releaseName: metallb
        namespace: metallb-system
  # Generator 2: MetalLB Manifests
  - git:
      repoURL: https://github.com/DanielScholtyssek/kindkube.git
      revision: HEAD
      directories:
      - path: infra/metallb/manifests
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
        argocd.argoproj.io/auto-sync: "true"
    spec:
      project: metallb-project
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        chart: '{{chart}}'
        path: '{{path}}'
        helm:
          releaseName: '{{releaseName}}'
          valuesObject:
            speaker:
              enabled: true
            controller:
              enabled: true
            prometheus:
              serviceMonitor:
                enabled: false
              rule:
                enabled: false
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
