apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb-applicationset
  namespace: argocd
spec:
  project: metallb-project
  generators:
  - git:
      repoURL: https://github.com/DanielScholtyssek/kindkube.git
      revision: HEAD
      directories:
      - path: infra/metallb/manifests
  template:
    metadata:
      name: 'metallb-{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "3"
        argocd.argoproj.io/auto-sync: "true"
    spec:
      project: metallb-project
      source:
        repoURL: https://github.com/DanielScholtyssek/kindkube.git
        targetRevision: HEAD
        path: '{{path}}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
