# Patch Contour deployment to run on control-plane node only
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contour
  namespace: projectcontour
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/role: control-plane
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
---
# Patch Envoy DaemonSet to run on control-plane node only  
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: envoy-contour
  namespace: projectcontour
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/role: control-plane
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
