apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/auto-sync: "true"
spec:
  project: contour-project
  source:
    repoURL: https://raw.githubusercontent.com/projectcontour/contour/main
    targetRevision: HEAD
    path: examples/gateway/00-crds.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
