apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: contour-project
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/DanielScholtyssek/kindkube.git
  - https://projectcontour.io/quickstart
  - https://raw.githubusercontent.com/projectcontour/contour/main
  destinations:
  - namespace: projectcontour
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  - namespace: metallb-system
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
