apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/auto-sync: "true"
spec:
  project: contour-project
  source:
    repoURL: https://github.com/DanielScholtyssek/kindkube.git
    targetRevision: HEAD
    path: infra/contour/provisioner
  destination:
    server: https://kubernetes.default.svc
    namespace: projectcontour
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
