apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: contour
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/DanielScholtyssek/kindkube.git
      revision: HEAD
      directories:
      - path: infra/contour/provisioner
  template:
    metadata:
      name: 'contour-provisioner'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
        argocd.argoproj.io/auto-sync: "true"
    spec:
      project: contour-project
      source:
        repoURL: https://github.com/DanielScholtyssek/kindkube.git
        targetRevision: HEAD
        path: 'infra/contour/provisioner'
      destination:
        server: https://kubernetes.default.svc
        namespace: projectcontour
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        retry:
          limit: 3
          backoff:
            duration: 2s
            factor: 1
            maxDuration: 30s
---
  - git:
      repoURL: https://github.com/DanielScholtyssek/kindkube.git
      revision: HEAD
      directories:
      - path: infra/contour/manifests
  template:
    metadata:
      name: 'contour-manifests'
      annotations:
        argocd.argoproj.io/sync-wave: "3"
        argocd.argoproj.io/auto-sync: "true"
    spec:
      project: contour-project
      source:
        repoURL: https://github.com/DanielScholtyssek/kindkube.git
        targetRevision: HEAD
        path: 'infra/contour/manifests'
      destination:
        server: https://kubernetes.default.svc
        namespace: projectcontour
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        retry:
          limit: 3
          backoff:
            duration: 2s
            factor: 1
            maxDuration: 30s
