apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: metallb-project
  namespace: argocd
spec:
  sourceRepos:
  - https://metallb.github.io/metallb
  - https://github.com/DanielScholtyssek/kindkube.git
  destinations:
  - namespace: metallb-system
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
