apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/auto-sync: "true"
spec:
  project: metallb-project
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: "0.15.3"
    helm:
      releaseName: metallb
      valuesObject:
        speaker:
          enabled: true
        controller:
          enabled: true
        prometheus:
          serviceMonitor:
            enabled: false
          rule:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 2s
        factor: 1.5
        maxDuration: 30s
